### ISSUE TITLE
关于内容中链接失效

### ISSUE THREAD

**Issue by hyhzzzz** [hh23333/PVPM#1]
作者您好！ Instructions regarding how to prepare Market1501 datasets can be found here.
但是here里面的链接已经404失效了

**Comment by hh23333** [comment]
您好，感谢您指出，代码基于deep-person-reid，链接更新为https://kaiyangzhou.github.io/deep-person-reid/datasets.html

**Comment by zsf882299** [comment]
作者您好：可以提供下openpose跑完了之后的结果吗

**Comment by hh23333** [comment]
> 作者您好：可以提供下openpose跑完了之后的结果吗

您好，目前疫情不在学校，存结果那个电脑没有开，您可以通过运行.scripts/openpose_*.sh得到openpose的结果

**Comment by zsf882299** [comment]
您好：我后来自己用openpose 跑了结果，但是和您论文里面公布的精度有很大偏差，想和您确认下如下信息：
(1)openpose输入图像的尺寸满足-1*384 (只对width=384,有限制，height没有限制是吗)，我用的pytorch版本的openpose
(2)训练数据是Market1501,测试数据是Occluded-REID， Partial-REID， P-DukeMTMC-reID？
我看您论文里面只说Occluded-REID， Partial-REID用来做测试， P-DukeMTMC-reID数据具体怎么用的呢，这里不是很清楚。麻烦您给指导下。
在2020年4月28日 16:51，hh23333<notifications@github.com> 写道：

作者您好：可以提供下openpose跑完了之后的结果吗

您好，目前疫情不在学校，存结果那个电脑没有开，您可以通过运行.scripts/openpose_*.sh得到openpose的结果

**Comment by hh23333** [comment]
1. 我使用的原版的openpose， -1代表图片比例不变自动自动计算，这个应该是是height限制为384
2. P-dukeMTMC-reID只用test数据做测试，遮挡图做probe，全身图做gallery；在P-duke上训练的话使用train文件夹下图片训练，训练方式和在market上相同，具体可参考https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/data/datasets/image/pduke_reid.py#L17

**Comment by zsf882299** [comment]
谢谢您的回复。我还有一个地方不是很清楚，在数据处理部分，例如pduke_reid.py里面数据集在加载姿势信息时：
104行 pose = cv2.imread(pose_pic_path, cv2.IMREAD_GRAYSCALE)，这里我理解的是pose_pic_path存储的是keypoint(18)+paf(38)  但是怎么存储在.png格式里面呢
还有就是pose[:,:,18:] = np.abs(pose[:,:,18:]-128)这里的pose是热度图吗，为什么还要减128呢
我觉得我跑的结果不对，很可能和这一部分理解不到位有关系，麻烦你给讲解下，谢谢哈

**Comment by hh23333** [comment]
第一个问题在另一个[issue](https://github.com/hh23333/PVPM/issues/2#issuecomment-620470056)里，那个减128就是我发现他输出的paf无关区域都是128，就减掉了，类似于去均值，但也没有做过不减的实验

**Comment by zsf882299** [comment]
好的，谢谢，明白了~

**Comment by zsf882299** [comment]
作者您好，我目前还有一个问题，我用您给出的代码只得到了跟PGA only 差不多的结果，您给的训练PVPM的脚本是PVPM+Aug的结果吗

**Comment by chenxiangzZ** [comment]
https://github.com/hh23333/PVPM/issues/1#issuecomment-625088877
你好，請問你復現的結果咋樣呢

**Comment by zsf882299** [comment]
没有复现出来

**Comment by hh23333** [comment]
转到issue #10 讨论吧，我把这个issue先关了哈
