### ISSUE TITLE
Can you ask me how to deal with the graph matching for testing?I know how to deal with training,but dont konw how to deal with in testing>

### ISSUE THREAD

**Issue by lhc11171552** [hh23333/PVPM#17]

**Comment by hh23333** [comment]
Graph matching is not used in testing, the goal of graph matching is only to generate the pseudo-lable for training the visibility predictor. When testing, visibility score is calculated by visibility predictor subnetwork.

**Comment by lhc11171552** [comment]
thank you very much

**Comment by lhc11171552** [comment]
So how to use local feature visibility when testing?

**Comment by hh23333** [comment]
![image](https://github.com/hh23333/PVPM/assets/28508213/087ee2ff-2bd6-4e8b-8669-6c30ee2238ee)
