### ISSUE TITLE
提取好的pose图

### ISSUE THREAD

**Issue by victor-gui** [hh23333/PVPM#3]
您好，我的openpose一直配置不成功，所以想请问你能不能把提取好的pose发给我一份呢，谢谢，我的邮箱：2574130682@qq.com

**Comment by GilbertTam** [comment]
hello author , i face the same question with @victor-gui can also mail me the picture link?
or how can you generate openpose .bin file in linux

**Comment by hh23333** [comment]
The Extracted pose maps can be found [here](https://pan.baidu.com/s/1Majze1iFo7FytREijmQO5A)(code:iwlz)

**Comment by r07942156** [comment]
Hello author, it seems that the link is not accessible anymore.
It shows:
啊哦，你所访问的页面不存在了。
可能的原因：
1.在地址栏中输入了错误的地址。
2.你点击的某个链接已过期。

Could you please provide the Google Cloud link? 
Thank you!

**Comment by hh23333** [comment]
@r07942156 the link is still valid. If you are not in China, VPN is recommended
