### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_cpu'

### ISSUE THREAD

**Issue by xhuljl** [hh23333/PVPM#4]
To Train PCB baseline
python scripts/main.py --root /home/huangk/PVPM/data/Market-1501-v15.09.15/ -s market1501 -t market1501 --save-dir /home/huangk/PVPM/data/Market-1501-v15.09.15/market_PCB -a pcb_p6 --gpu-devices 0 --fixbase-epoch 0 --open-layers classifier fc --new-layers classifier em --transforms random_flip --optim sgd --lr 0.02 --stepsize 25 50 --staged-lr --height 384 --width 192 --batch-size 32 --base-lr-mult 0.5
** Arguments **
adam_beta1: 0.9
adam_beta2: 0.999
app: image
arch: pcb_p6
base_lr_mult: 0.5
batch_size: 32
combineall: False
cuhk03_classic_split: False
cuhk03_labeled: False
dist_metric: euclidean
eval_freq: -1
evaluate: False
fixbase_epoch: 0
gamma: 0.1
gpu_devices: 0
graph_matching: False
height: 384
label_smooth: False
load_pose: False
load_weights: 
loss: softmax
lr: 0.02
lr_scheduler: multi_step
margin: 0.3
market1501_500k: False
max_epoch: 60
momentum: 0.9
new_layers: ['classifier', 'em']
no_pretrained: False
normalize_feature: False
num_att: 6
num_instances: 4
open_layers: ['classifier', 'fc']
optim: sgd
part_score: False
pooling_method: avg
print_freq: 20
ranks: [1, 3, 5, 10, 20]
reg_matching_score_epoch: 5
rerank: False
resume: 
rmsprop_alpha: 0.99
root: /home/huangk/PVPM/data/Market-1501-v15.09.15/
sample_method: evenly
save_dir: /home/huangk/PVPM/data/Market-1501-v15.09.15/market_PCB
seed: 1
seq_len: 15
sgd_dampening: 0
sgd_nesterov: False
sources: ['market1501']
split_id: 0
staged_lr: True
start_epoch: 0
start_eval: 0
stepsize: [25, 50]
targets: ['market1501']
train_sampler: RandomSampler
transforms: ['random_flip']
use_att_loss: False
use_avai_gpus: False
use_cpu: False
use_metric_cuhk03: False
visrank: False
visrank_topk: 20
weight_decay: 0.0005
weight_t: 1
weight_x: 0
width: 192
workers: 4

Collecting env info ...
** System info **
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.43
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1
[pip3] torchreid==1.2.5
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] mkl                       2020.1                      217    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.3.0            py37he904b0f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.1.0            py37h23d657b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.1.1            py37h0573a6f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.5.1           py3.7_cuda10.1.243_cudnn7.6.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchreid                 1.2.5                     dev_0    <develop>
[conda] torchvision               0.6.1                py37_cu101    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
        Pillow (7.1.2)

Traceback (most recent call last):
  File "scripts/main.py", line 163, in <module>
    main()
  File "scripts/main.py", line 130, in main
    datamanager = build_datamanager(args)
  File "scripts/main.py", line 27, in build_datamanager
    return torchreid.data.ImageDataManager(**imagedata_kwargs(args))
TypeError: __init__() got an unexpected keyword argument 'use_cpu'

What is the cause? Your help will be greatly appreciated.

**Comment by hh23333** [comment]
Please check code [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/data/datamanager.py#L117). and [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/data/datamanager.py#L26) sure that the argument 'use_cpu' is still in the argument list. Also, we recommend you to use python2.7 and pytorch 1.0 to reproduce our work avoiding some minor problems.

**Comment by hh23333** [comment]
Please check code [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/data/datamanager.py#L26) and [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/data/datamanager.py#L117) to make sure that the argument 'use_cpu' is still in the argument list. Also, we recommend you to use python2.7 and pytorch 1.0 to reproduce our work avoiding some minor problems.

**Comment by xhuljl** [comment]
Thank you. The problem has been solved
My solution is to modify the following [code](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/scripts/main.py#L27).
