### ISSUE TITLE
AttributeError: 'module' object has no attribute 'pose_resnet50_256_global'

### ISSUE THREAD

**Issue by nanHeK** [hh23333/PVPM#5]
Hello,What is the cause? Your help will be greatly appreciated.
python setup.py develop 
python 2.7

(torchreid27) huangk@john-b:~/PVPM$ python setup.py develop
/home/huangk/PVPM/torchreid/metrics/rank.py:17: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    version=find_version(),
  File "setup.py", line 16, in find_version
    exec(compile(f.read(), version_file, 'exec'))
  File "torchreid/__init__.py", line 8, in <module>
    from torchreid import (
  File "/home/huangk/PVPM/torchreid/__init__.py", line 8, in <module>
    from torchreid import (
  File "/home/huangk/PVPM/torchreid/models/__init__.py", line 27, in <module>
    from .pcb import *
AttributeError: 'module' object has no attribute 'pose_resnet50_256_global'

**Comment by hh23333** [comment]
Sorry for this mistake. Just delete 'pose_resnet50_256_global' [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/models/pcb.py#L4) will solve this error.

**Comment by nanHeK** [comment]
Thank you .delete [here] also(https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/models/__init__.py#L71)

**Comment by nanHeK** [comment]
Thanl you . delate [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/models/__init__.py#L71) also
