### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by nanHeK** [hh23333/PVPM#6]
To train PVPM
Have you ever tested Occluded_ Duke dataset? I didn't find the dataset [here](https://github.com/hh23333/PVPM/blob/633a13acd271b0de2ebddcdf9cdde3f2e6a31d46/torchreid/data/datasets/__init__.py#L9).
In addition, can I use this dataset when I train or test.
Thank you very much for your help and answer.

**Comment by hh23333** [comment]
Yes, PVPM can also brings improvements on Occluded_Duke. We will upload dataset_loader file latter.

**Comment by nanHeK** [comment]
Thank you for your data loading class. Does the author use occluded_ Duke data set, the effect of my side running out is not very ideal in occluded_ Duke dataset, maybe it's my problem. If you can share the effect of rank-1, I'll thank you very much. In addition, I would like to express my great respect for your work.

**Comment by hh23333** [comment]
We trained the PCB baseline model on o-duke and got the following result:
```
mAP: 32.9%
CMC curve
Rank-1  : 39.8%
Rank-5  : 54.2%
Rank-10 : 59.8%
Rank-20 : 65.7%
```
and our PVPM method got:
```
mAP: 37.7%
CMC curve
Rank-1  : 47.0%
Rank-3  : 57.9%
Rank-5  : 63.0%
Rank-10 : 69.1%
Rank-20 : 73.9%
```

**Comment by nanHeK** [comment]
Thank you very much for your patient guidance and help. The problem mentioned before may be my bug. I am very sorry to disturb your time. Your data has been very helpful to me. Thank you again and wish you all the best.
